- hosts: localhost
  become: true
  roles:
  - { role: elasticsearch, tags: ["elasticsearch"] }
  - { role: kibana, tags: ["kibana"] }
  - { role: logstash, tags: ["logstash"] }
  - { role: heartbeat, tags: ["heartbeat"] }
  - { role: filebeat, tags: ["filebeat"] }
  - { role: metricbeat, tags: ["metricbeat"] }